name: Issue Management
on:
  issue_comment:
    types: [created]
jobs:
  get-issue-parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.TOKEN }}" | gh auth login --with-token

      - name: Check GitHub CLI Authentication
        run: gh auth status

      - name: Get Project Number
        id: get_project
        run: |
          PROJECT_NUMBER=$(gh project list --format json | jq -r '.projects[] | select(.title=="githubproject") | .number')
          echo "PROJECT_NUMBER=${PROJECT_NUMBER}" >> $GITHUB_ENV

      - name: Get Issue ID
        id: get_issue_id
        run: |
          ISSUE_ID=$(gh project item-list "${PROJECT_NUMBER}" --owner "@me" --format json | jq -r --arg issue "${{ github.event.issue.number }}" '.items[] | select(.content.number==($issue | tonumber)) | .id')
          echo "ISSUE_ID=${ISSUE_ID}" >> $GITHUB_ENV

      - name: Get Field ID
        id: get_field_id
        run: |
          FIELD_ID=$(gh project field-list "${PROJECT_NUMBER}" --owner "@me" --format json | jq -r '.fields[] | select(.name=="Status") | .id')
          echo "FIELD_ID=${FIELD_ID}" >> $GITHUB_ENV

      - name: Get Option IDs
        id: get_option_ids
        run: |
          INPROGRESS_OPTION_ID=$(gh project field-list "${PROJECT_NUMBER}" --owner "@me" --format json | jq -r '.fields[] | select(.name=="Status") | .options[] | select(.name=="In progress") | .id')
          DONE_OPTION_ID=$(gh project field-list "${PROJECT_NUMBER}" --owner "@me" --format json | jq -r '.fields[] | select(.name=="Status") | .options[] | select(.name=="Done") | .id')
          echo "INPROGRESS_OPTION_ID=${INPROGRESS_OPTION_ID}" >> $GITHUB_ENV
          echo "DONE_OPTION_ID=${DONE_OPTION_ID}" >> $GITHUB_ENV

  move-issue:
    runs-on: ubuntu-latest
    needs: get-issue-parameters
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move Issue to In-Progress
        if: contains(github.event.comment.body, 'progress')
        run: |
          echo "Moving to In-Progress"
          gh project item-edit --id "${{ env.ISSUE_ID }}" --field-id "${{ env.FIELD_ID }}" --project-id "${{ env.PROJECT_NUMBER }}" --single-select-option-id "${{ env.INPROGRESS_OPTION_ID }}"
        env:
          GH_TOKEN: ${{ github.token }}
